### ISSUE TITLE
Newest builddb Management Command does not execute

### ISSUE THREAD

**Issue by jcockhren** [solanum-tuberosums/bangazonOrientationAPI#57]
# Associated Ticket
#50 
Pull Request: #54 

### Expected Behavior

Commands should build database and inject fixture data.

### Actual Behavior
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jurnell/.tools/virtualenv/bang-nss/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/jurnell/.tools/virtualenv/bang-nss/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jurnell/.tools/virtualenv/bang-nss/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 205, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/jurnell/.tools/virtualenv/bang-nss/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named management.commands.builddb
```

### Steps to Reproduce
1. Follow the setup steps from the README.
2. Run `python manage.py builddb`

**Comment by zakspence** [comment]
@jcockhren you're running python 2.7 it looks like. Could you try it on python 3.6?

**Comment by JeremyBakker** [comment]
![image](https://cloud.githubusercontent.com/assets/24864800/25447275/25eec9f8-2a7a-11e7-99bf-a23613aef32f.png)

**Comment by JeremyBakker** [comment]
Team, check http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html

I think it has the root of the bug.

**Comment by zakspence** [comment]
@jcockhren I tried running the command in an environment with python 2.7 and got the same error. Looks like it's just your python environment needs to be running python 3.

**Comment by jcockhren** [comment]
@zakspence confirmed. command works so far.
